version: '3.6'
services:
  node:
    container_name: node
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - services-tier
    ports:
      - $GLS_CONNECTOR_HOST:$GLS_CONNECTOR_PORT:$GLS_CONNECTOR_PORT
    environment:
      - GLS_FRONTEND_GATE_CONNECT
      - GLS_ONLINE_NOTIFY_CONNECT
      - GLS_NOTIFY_CONNECT
      - GLS_OPTIONS_CONNECT
      - GLS_PUSH_CONNECT
      - GLS_MAIL_CONNECT
      - GLS_REGISTRATION_CONNECT
      - GLS_RATES_CONNECT
      - GLS_DAY_START
      - GLS_METRICS_HOST
      - GLS_METRICS_PORT
      - GLS_CONNECTOR_HOST
      - GLS_CONNECTOR_PORT

networks:
  services-tier:
